--1
SELECT NAME, COUNTRY, NUMGUNS, LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS;


--2
SELECT NAME, COUNTRY, NUMGUNS, LAUNCHED
FROM CLASSES LEFT JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS OR SHIPS.NAME = CLASSES.CLASS;


--3
SELECT SHIP
FROM OUTCOMES JOIN BATTLES ON BATTLE = NAME
WHERE DATE LIKE "%1942%";


--4
SELECT *
FROM SHIPS LEFT JOIN OUTCOMES ON NAME = SHIP
WHERE BATTLE IS NULL;







